### ISSUE TITLE
rviz中无地图显示

### ISSUE THREAD

**Issue by zxl19** [Little-Potato-1990/lidar_localization#4]
您好@Little-Potato-1990 ！我按照教程安装了功能包并转换了rosbag，但是在算法运行时rviz中没有地图显示，并且报错`Fixed Frame [map] does not exist`，请问这是rosbag转换的问题吗？我使用的是KITTI数据集的另一个原始数据序列，但是和您文档中的转换方式是相同的。

**Comment by zxl19** [comment]
除此之外，在`back_end.yaml`文件中有这样的设置，这是否合理？

```yaml
optimize_step_with_key_frame: 10000 # optimize with every "optimize_step_with_key_frame" new key frame 
optimize_step_with_gnss: 950 # optimize with every "optimize_step_with_gnss" new gnss constraint
optimize_step_with_loop: 100  # optimize with every "optimize_step_with_loop" new loop close constraint
```
